language: node_js
cache: yarn
node_js: '10'
install: yarn install
script: yarn build
notifications:
  email: false
before_deploy:
  - openssl aes-256-cbc -K $encrypted_c6cd6593e4d8_key -iv $encrypted_c6cd6593e4d8_iv -in deploy_key.enc -out ./deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
deploy:
  provider: script
  script:
    echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > $HOME/.npmrc && yarn release-it -n --preRelease=alpha
  skip_cleanup: true
