language: node_js
cache: yarn
node_js: "10"
install: yarn install
script: yarn build
notifications:
  email: false
deploy:
  provider: script
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > $HOME/.npmrc
    - npm publish
