language: node_js
cache: yarn
node_js: "10"
install: yarn install
script: yarn build
notifications:
  email: false
deploy:
  provider: npm
  email: "ekoeryanto@gmail.com"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
